theme: jekyll-theme-architect
name: Nikolaos Iliopoulos
description: Custom RGB Controller
show_downloads: true
markdown: GFM
footer-links:
  email: nilioprobots@gmail.com
  facebook: https://www.facebook.com/nikolaosiliopoulosrobotics
  github: https://github.com/nickiliopoulosedu/
  instagram: https://www.instagram.com/_nick_iliopoulos_/
  stackoverflow: https://stackoverflow.com/users/13347441/nikolaos-iliopoulos
  youtube: https://www.youtube.com/channel/UCIqK_Ubw_gnUNMHHzz3yyZg
